export const GET_Day_Data='GET_Day_Data';
export const GET_Month_Data='GET_Month_Data';
export const GET_Year_Data='GET_Year_Data';
export const GET_Week_Data='GET_Week_Data';
export const GET_Day_Data_By_Date ='GET_Day_Data_By_Date';
export const CLEAR_DATA='CLEAR_DATA';
export const SET_SEARCH='SET_SEARCH';
export const COUNT=`COUNT`
export const COUNT_LINK=`COUNT_LINK`
export const DEPARTMENT ='DEPARTMENT'
export  const WAREHOUSE='WAREHOUSE'
export const PRODUCT_ID='PRODUCT_ID'